name: Rapport Quotidien
on:
  schedule:
    - cron: '0 8 * * *'  # Se lance chaque matin à 8h00 UTC
  workflow_dispatch:      # Ajoute un bouton pour le lancer à la main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v3
      - name: Installer Python
        run: pip install requests
      - name: Lancer le robot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
        
